# Generated by Django 5.0.4 on 2024-04-10 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('date_peek', models.DateField()),
                ('popularity', models.IntegerField()),
                ('path_to_img', models.ImageField(upload_to='memes/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('email', models.CharField(max_length=100)),
                ('favorites', models.ManyToManyField(to='Site.meme')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Site.status')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.account')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.BooleanField(default=False)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='Site.account')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.account')),
            ],
            options={
                'unique_together': {('user_id', 'friend_id')},
            },
        ),
    ]
