# Generated by Django 5.0.4 on 2024-05-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
