# Generated by Django 5.0.4 on 2024-05-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_remove_meme_path_to_img_memegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='path_to_img',
            field=models.ImageField(default='deadimage', upload_to='memes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memegallery',
            name='image',
            field=models.ImageField(upload_to='galery/memes/'),
        ),
    ]
