# Generated by Django 5.0.4 on 2024-05-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_meme_path_to_img_alter_memegallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='link',
            new_name='accepted',
        ),
    ]
