# Generated by Django 5.0.4 on 2024-05-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_rename_link_friend_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
