# Generated by Django 5.0.4 on 2024-05-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_rename_link_friend_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend_id',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='memegallery',
            old_name='meme_id',
            new_name='meme',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='date_peek',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='popularity',
        ),
        migrations.AlterField(
            model_name='meme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('user', 'friend')},
        ),
        migrations.AlterUniqueTogether(
            name='memegallery',
            unique_together={('meme', 'image')},
        ),
        migrations.AddField(
            model_name='meme',
            name='genre',
            field=models.ManyToManyField(to='Site.genres'),
        ),
    ]
