# Generated by Django 5.0.4 on 2024-05-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_genres_rename_friend_id_friend_friend_and_more'),
        ('Site', '0007_site_account_favorites_alter_account_username'),
    ]

    operations = [
    ]
