# Generated by Django 5.0.4 on 2024-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_remove_meme_genre_delete_site_account_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='cultural_influence',
            field=models.TextField(default='Тогда почему ты мой писарь, а? (404)'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='description',
            field=models.TextField(default='Тогда почему ты мой писарь, а? (404)'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='history',
            field=models.TextField(default='Тогда почему ты мой писарь, а? (404)'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='meaning',
            field=models.TextField(default='Тогда почему ты мой писарь, а? (404)'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='using_examples',
            field=models.TextField(default='Тогда почему ты мой писарь, а? (404)'),
        ),
    ]
